version: "3.8"
services:
  app:
    image: tts-stream-app:latest
    container_name: tts-app
    ports:
      - "5000:5000"
    environment:
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=2
    volumes:
      - ./tts/app_cluster.py:/app/app_cluster.py
      - ./tts/templates:/app/templates
      - ./tts/data:/app/data
      - ./tts/data/tts-models:/app/data/tts-models
    networks:
      - funasr-network
    restart: unless-stopped


  funasr-offline:
    image: funasr-offline:1.0.0
    container_name: funasr-offline
    ports:
      - "8000:8000"
    environment:
      - ASR_MODEL=paraformer-zh
      - VAD_MODEL=fsmn-vad
      - PUNC_MODEL=ct-punc-c
      - DEVICE=cpu
      - NGPU=0
      - NCPU=4
    volumes:
      - ./funasr-offline/temp_dir:/app/temp_dir
      - ./funasr-offline/data:/app/data
      - ./funasr-offline/templates:/app/templates
      - ./funasr-offline/hotwords.txt:/app/hotwords.txt
      # 添加 server.py 挂载以便于修改
      - ./funasr-offline/server.py:/app/server.py
      # 添加模型目录挂载
      - ./funasr-offline/models:/root/.cache/modelscope/hub/models
    networks:
      - funasr-network
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx-asr-tts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tts/data:/app/data:rw
      # 添加文档目录映射
      - ./nginx/doc:/usr/share/nginx/doc:ro
      - ./nginx/cert/mk-cert.pem:/etc/nginx/cert/mk-cert.pem
      - ./nginx/cert/mk-key.pem:/etc/nginx/cert/mk-key.pem
    networks:
      - funasr-network
    restart: unless-stopped

networks:
  funasr-network:
    driver: bridge




